mqtt:
  broker:
    url: tcp://localhost:1883
    subscribe: iotmessage
    produce: iotcommand

db:
  url: http://localhost:8086
  token: mXgveOzEYOuSiN0fAy29EM2sqZccAI9bd9ADD4ptZvTFD2mi6GJZkG3L1E42DfQB6qUWp-LWSaNprNNWUWtfUw==
  